### ISSUE TITLE
Error or success ? "Could not get the screen info"

### ISSUE THREAD

**Issue by joe-mojo** [fusesource/jansi#158]
logback with JANSI on Windows 10 failed with this cause:
```
Caused by: java.io.IOException: Could not get the screen info: L'opération a réussi.
        at      at org.fusesource.jansi.WindowsAnsiOutputStream.getConsoleInfo(WindowsAnsiOutputStream.java:116)
        at      at org.fusesource.jansi.WindowsAnsiOutputStream.<init>(WindowsAnsiOutputStream.java:105)
        at      at org.fusesource.jansi.WindowsAnsiOutputStream.<init>(WindowsAnsiOutputStream.java:110)
```
"L'opération a résussi" means "operation was successful" in french.
So throwing an error when a success is reported is quite strange...

**Comment by gnodet** [comment]
This could happen if the stream wrapped by Jansi is not the system out stream or if the system out is not the windows console (for example if redirected to a file).

I agree the message is weird, but if there is a definitely an error when accessing the console.

**Comment by gnodet** [comment]
I don't think there's anything to do and we'd need at least a way to reproduce the problem.
