### ISSUE TITLE
No native library for Mac arm64

### ISSUE THREAD

**Issue by electrum** [fusesource/jansi#218]
It would be nice if Jansi worked on the M1 so that colors work in Maven.

**Comment by mattsalt** [comment]
Colours worked on maven 3.8.1 using Jansi 1.17.1 but not in maven 3.8.2 using Jansi 2.3.4

**Comment by mattsalt** [comment]
Looks like there was no native method in 2.0.1 either but the exception was caught and defaulted to `RESET_ANSI_AT_CLOSE`

**Comment by electrum** [comment]
I found that colors still work with `-Dstyle.color=always`.

**Comment by mattsalt** [comment]
That's handy. `alias mvn="mvn -Dstyle.color=always` it is then.

**Comment by davsclaus** [comment]
Anyone tracked down why colors stopped workin in 2.1.1?

I dont have colours either in mvn 3.8.2

**Comment by gnodet** [comment]
> Anyone tracked down why colors stopped workin in 2.1.1?
> 
> I dont have colours either in mvn 3.8.2

Which platform / os ?

**Comment by davsclaus** [comment]
@gnodet btw when you use maven 3.8.3, and mvnd 0.6.0 then you have this on aarch64 mac apple m1

```
mvnd --version
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:91)
Caused by: java.lang.RuntimeException: Unable to load jansi native library
	at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:62)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:30)
	... 1 more
Caused by: java.lang.Exception: No native library found for os.name=Mac, os.arch=aarch64, paths=[/opt/homebrew/Cellar/mvnd/0.6.0/libexec/mvn/lib/jansi-native/Mac/aarch64:/opt/homebrew/Cellar/mvnd/0.6.0/libexec/mvn/lib/jansi-native:/Users/davsclaus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
	at org.fusesource.jansi.internal.JansiLoader.loadJansiNativeLibrary(JansiLoader.java:333)
	at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:60)
	... 2 more
```

So if we can get jansi to support aarch64 and into a new release then mvnd could use that and get this working ;)

**Comment by gnodet** [comment]
Could you try the #222 PR and see if the library is valid ?
Simply building jansi and replacing the binary in mvnd / mvn installation should do the trick...
I can't really test it with my x64 Mac ;-)

**Comment by davsclaus** [comment]
@gnodet not sure if I should build it in another way, this is what I did, see the gist
https://gist.github.com/davsclaus/28fb6898dbe23cf8971a43aa892cdbfe

**Comment by gnodet** [comment]
> @gnodet not sure if I should build it in another way, this is what I did, see the gist https://gist.github.com/davsclaus/28fb6898dbe23cf8971a43aa892cdbfe
> 
> And this is with your PR merged.
> 
> commit [5fe9293](https://github.com/fusesource/jansi/commit/5fe9293a9985da947787edd94acb63a87a826715) (HEAD -> gnodet-mac-arm64) Author: Guillaume Nodet [gnodet@gmail.com](mailto:gnodet@gmail.com) Date: Tue Oct 5 11:54:15 2021 +0200
> 
> ```
> Support Mac-arm64 target, fixes #218
> ```

@davsclaus , this looks like maven is shading the being-built version of jansi. Could you comment the `exec-maven-plugin` plugin from the pom so that you can actually build jansi ?

Then simply run the following command and give the output ?
```
java -jar target/jansi-2.3.5-SNAPSHOT.jar
```

**Comment by davsclaus** [comment]
Thanks, here is the output
https://gist.github.com/davsclaus/be3c988a59ec1bd3042964458159adfb
