### ISSUE TITLE
Out Of Memory happened during fuzzing test

### ISSUE THREAD

**Issue by baltsers** [fusesource/jansi#239]
***Description***
An OOM issue happened during the fuzzing test of class "AnsiOutputStream".
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
        at org.fusesource.jansi.io.AnsiProcessor.processCursorDownLine(AnsiProcessor.java:517)
        at org.fusesource.jansi.io.AnsiProcessor.processEscapeCommand(AnsiProcessor.java:75)
        at org.fusesource.jansi.io.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:304)
        at org.fusesource.jansi.io.AnsiOutputStream.write(AnsiOutputStream.java:204)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
        at OsJansi.OutStream.main(OutStream.java:64)
```

***Environment***
1. openjdk version "1.8.0_275" & Ubuntu 18.04
2. jansi: the latest (the main branch)

***Code***
We upload the code and correspond input to the [link](https://github.com/baltsers/polyfuzz/tree/main/jansi).
To reproduce the bug:
<1> cd jansi && ./build.sh
<2> ./run.sh

**Comment by baltsers** [comment]
anyone can help confirm this issue? thanks

**Comment by gnodet** [comment]
@baltsers the link is not available anymore
