### ISSUE TITLE
Exception if path is relative

### ISSUE THREAD

**Issue by ptahchiev** [fusesource/jansi#25]
Hi guys,

I know this is probably a java issue, but still I want to ask if you have this problem. I'm using Java Service Wrapper from Tanukisoftware and when I start my application I get this exception in the log:
: [no jansi64-1.11 in java.library.path, no jansi-1.11 in java.library.path, no jansi in java.library.path, Expecting an
 absolute path of the library: .\temp\jansi-64-1-2053084745145975388.11]
INFO   | jvm 1    | 2013/11/29 14:37:57.839 |   at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
INFO   | jvm 1    | 2013/11/29 14:37:57.842 |   at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
INFO   | jvm 1    | 2013/11/29 14:37:57.843 |   at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
INFO   | jvm 1    | 2013/11/29 14:37:57.850 |   at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutp
utStream.java:52)
INFO   | jvm 1    | 2013/11/29 14:37:57.852 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

INFO   | jvm 1    | 2013/11/29 14:37:57.853 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:57)
INFO   | jvm 1    | 2013/11/29 14:37:57.857 |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2013/11/29 14:37:57.858 |   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2013/11/29 14:37:57.860 |   at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStrea
m(ConsoleAppender.java:128)
INFO   | jvm 1    | 2013/11/29 14:37:57.863 |   at org.apache.logging.log4j.core.appender.ConsoleAppender.getManager(Con
soleAppender.java:104)
INFO   | jvm 1    | 2013/11/29 14:37:57.865 |   at org.apache.logging.log4j.core.appender.ConsoleAppender.createAppender
(ConsoleAppender.java:99)
INFO   | jvm 1    | 2013/11/29 14:37:57.868 |   ... 53 more
INFO   | jvm 1    | 2013/11/29 14:37:57.871 |

As you can see it's expecting an absolute path for the dll file in the META-INF, but JSW is extracting it to a temp folder under the main directory, so the result is ./temp/jansi which throws an exception.

Do you think there's a way to change jansi in such a way that it doesn't throw an exception if the path is relative?

**Comment by gnodet** [comment]
Closing due to inactivity. Please reopen after testing on 2.0.x if needed.
