### ISSUE TITLE
java.lang.IllegalArgumentException on intergration test execution

### ISSUE THREAD

**Issue by cherifdeme** [fusesource/jansi#295]
Hi,
I have this error message below on Giltab Runner with params. -Djansi.force=true -Dstyle.color=always. 
When I get to the execution of my integration test it displays:

java.lang.IllegalArgumentException
	at org.fusesource.jansi.io.AnsiProcessor.getNextOptionInt(AnsiProcessor.java:49)
	at org.fusesource.jansi.io.ColorsAnsiProcessor.processEscapeCommand(ColorsAnsiProcessor.java:68)
	at org.fusesource.jansi.io.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:304)
	at org.fusesource.jansi.io.AnsiOutputStream.write(AnsiOutputStream.java:189)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
	at java.base/java.io.PrintStream.write(PrintStream.java:568)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
	at java.base/java.io.Writer.write(Writer.java:249)
	at java.base/java.io.PrintStream.write(PrintStream.java:697)
	at java.base/java.io.PrintStream.print(PrintStream.java:863)
	at java.base/java.io.PrintStream.println(PrintStream.java:1031)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
	
when I remove the line -Dstyle.color=always, anything is OK
Do you have any idea about the origin of the problem?
Envi: spring boot 3/log4j-slf4j2-impl:2.21.1/maven 3.9.6

Best regards

**Comment by cherifdeme** [comment]
ras
